# Rakefile
#                           wookay.noh at gmail.com

require '../unittest/build.rb'

task :default do
  sh "rake -T --silent"
end

make 'p' do |m|
  m.compile 'pari_gp_ext.c', '-I/usr/local/include'
  m.compile 'GP.m'
  m.compile 'GPTest.m'
  m.link '-lpari'
  m.run
  m.clean
end
