# Makefile
#                           wookay.noh at gmail.com

all:
	@cd unittest && make
	@cd foundation && make
	@cd appkit && make
	@cd quartzcore && make
	@cd scriptingbridge && make
	@cd math && make

t:
	@cd unittest && make t
	@cd foundation && make t
	@cd appkit && make t
	@cd quartzcore && make t
	@cd scriptingbridge && make t
	@cd math && make t

p:
	@cd unittest && make p
	@cd foundation && make p
	@cd appkit && make p
	@cd quartzcore && make p
	@cd scriptingbridge && make p
	@cd math && make p

clean:
	cd unittest && make clean
	cd foundation && make clean
	cd appkit && make clean
	cd quartzcore && make clean
	cd scriptingbridge && make clean
	cd math && make clean
