# Makefile
#                           wookay.noh at gmail.com

all:
	cd unittest && make && ./test
	cd foundation && make && ./test
	cd appkit && make && ./test
	cd scriptingbridge && make && ./test

clean:
	cd unittest && make clean
	cd foundation && make clean
	cd appkit && make clean
	cd scriptingbridge && make clean
