# Rakefile
#                           wookay.noh at gmail.com

IGNORE_FILES = %w{appkit README Rakefile touch macruby uikit pari_gp_ext test.m twitter}
load 'unittest/build.rake'

require 'unittest/build.rb'
make 'test.m' do |m|
  m.compile 'test.m'
  m.link
  m.run
  m.clean
end
