# Rakefile
#                           wookay.noh at gmail.com

IGNORE_FILES = %w{
README         build_script/  fun/           quartzcore/    uikit/
Rakefile       cg/            hangul/        stackoverflow/ vlaah/
UnitTest/      chipmunk/      math/          test.m
appkit/        coregraphics/  me2day/        touch/
arabic/                       pari_gp_ext/   twitter/
}.map{|f| f.gsub('/','')}

load 'build_script/build.rake'

require 'build_script/build.rb'
make 'test.m' do |m|
  m.compile 'test.m'
  m.link
  m.run
  m.clean
end
