# Rakefile
#                           wookay.noh at gmail.com

CLASSES    = %w{UnitTestCategory} + Dir['src/*.c']
FRAMEWORKS = %w{Foundation}
CLEANUP    = 'src/*.o ../unittest/*.o'

DIR = File.dirname __FILE__
load '../unittest/build.rake'
