# Rakefile
#                           wookay.noh at gmail.com

CLASSES    = %w{Enumerable Numeric String Array Hash}
FRAMEWORKS=%w{Foundation}

DIR = File.dirname __FILE__
load '../unittest/build.rake'
