# oo

OO_VERSION=0.1
OO_COPYRIGHT="Oo - Copyright (C) 2008 Woo-Kyoung Noh"

PASSED="passed"
ASSERTION_FAILED="Assertion failed"
EXPECTED="Expected"
GOT="Got"

RULES_PREFERENCES="rules/.preferences"
RULES_PRI="rules/.pri"

POSTPOSITION_NOMINATIVE="이|가"
POSTPOSITION_OBJECTIVE="을|를"
POSTPOSITION_DESCRIPTIVE="다|이다|이 아니다|가 아니다"
POSTPOSITION_POSSESSIVE="의"
POSTPOSITION_ADJECTIVE="에|에서|에게|한|한테|로|으로|로써|으로써"
POSTPOSITION_VOCATIVE="아|야|여|이여|시여|이시여"
POSTPOSITION_CONJUCTIVE="와|과|며|이며|고|이고|랑|에다"
POSTPOSITION_SUPPORTING="은|는|도|만|조차|부터|까지|나|이나|마저|밖에|일때"
POSTPOSITIONS=[POSTPOSITION_NOMINATIVE, POSTPOSITION_OBJECTIVE, POSTPOSITION_DESCRIPTIVE, POSTPOSITION_POSSESSIVE, POSTPOSITION_ADJECTIVE, POSTPOSITION_VOCATIVE, POSTPOSITION_CONJUCTIVE, POSTPOSITION_SUPPORTING]

KEYWORD_ARGUMENTS="인자값"
KEYWORD_RULES="규칙"
KEYWORD_WHAT="뭐|뭐임"
KEYWORD_ORDER="키순서"
KEYWORD_NO="모르오"
KEYWORD_FUNCTION="함수"
KEYWORD_INVERSE_FUNCTION="역함수"
KEYWORD_CODE="코드"
KEYWORD_PATTERNS="패턴"
KEYWORD_COMPOSITIONS="조합"
KEYWORDS = [KEYWORD_ARGUMENTS, KEYWORD_RULES, KEYWORD_WHAT, KEYWORD_ORDER, KEYWORD_NO, KEYWORD_FUNCTION, KEYWORD_INVERSE_FUNCTION, KEYWORD_CODE, KEYWORD_PATTERNS, KEYWORD_COMPOSITIONS]
