# Rakefile
#                           wookay.noh at gmail.com

task :default do
  sh "rake -T"
end

desc "run tests"
task :t do
  run_tests true
end

desc "run tests and display only results"
task :p do
  run_tests
end

def run_tests show_ret=false
  dirs = Dir['*.gp'].select{|gp|gp=~/^test/}
  dirs.each do |gp|
    ret = `gp -q #{gp}` 
    if show_ret
      puts gp
      ret.split("\n").each do |line|
        puts "  #{line}"
      end
    else
      print "#{gp.ljust dirs.map{|x|x.size}.max} "
    end
    passed = ret.scan(/^passed: /).size
    failed_message = ret.split("\n").reject{|line|line =~ /^passed/}
    failed = failed_message.select{|line|line =~ /^Assertion failed/}.size
    puts "\n#{failed_message.join"\n"}" if not failed_message.empty?
    puts "OK, passed #{passed} test#{'s' if passed > 1}."
    puts "Oops, failed #{failed} test#{'s' if failed > 1}." if failed > 0
  end
end
