# Rakefile
#                           wookay.noh at gmail.com

PROGRAM_RUN = './Oo'
PROGRAM_EXTENSION = 'oo'

task :default do
  sh "rake -T"
end

desc "run tests"
task :t do
  run_tests true
end

desc "run tests and display only results"
task :p do
  run_tests
end

using_network = %w{youtube.oo}
task :n do
  files= Dir["*.#{PROGRAM_EXTENSION}"].reject{|file|file=~/^test/}.reject{|file| using_network.include? file}
  files.each do |file|
    ret = `#{PROGRAM_RUN} #{file}` 
    puts ret
  end
end

def run_tests show_ret=false
  files = Dir["*.#{PROGRAM_EXTENSION}"].select{|file|file=~/^test/}
  files.each do |file|
    ret = `#{PROGRAM_RUN} #{file}` 
    if show_ret
      puts file
      ret.split("\n").each do |line|
        puts "  #{line}"
      end
    else
      print "#{file.ljust files.map{|x|x.size}.max}  "
    end
    passed = ret.scan(/^passed: /).size
    failed_message = ret.split("\n").reject{|line|line =~ /^passed/}
    failed = failed_message.select{|line|line =~ /^Assertion failed/}.size
    puts "\n#{failed_message.join"\n"}" if not failed_message.empty?
    puts "OK, passed #{passed} test#{'s' if passed > 1}."
    puts "Oops, failed #{failed} test#{'s' if failed > 1}." if failed > 0
  end
end
