# Rakefile
#                           wookay.noh at gmail.com

CLASSES    = %w{base topic person comment comment_list commenter_list unit}
FRAMEWORKS = %w{Foundation}

DIR = File.dirname __FILE__
load '../unittest/build.rake'
